[package]
name = "inherit"
version = "0.1.0"
authors = ["Mark S. Baranowski <mark.s.baranowski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
